package de.minimum.hawapp.app.calendar.beans;

// Generated 26.04.2013 13:35:12 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CalendarAppointment generated by hbm2java
 */
public class AppointmentPO implements AppointmentBO, java.io.Serializable {

    @Override
    public String toString() {
        final DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.SHORT,
                        Locale.GERMANY);
        return "Termin" + name + " \n" + dateFormat.format(begin) + " - " + dateFormat.format(end) + "\n Ort "
                        + location;
    }

    private static final long serialVersionUID = 1L;
    private String uuid;
    private LecturePO lecture;
    private String name;
    private Date begin;
    private Date end;
    private String location;
    private String details;
    private Date lastModified;

    public AppointmentPO() {
    }

    public AppointmentPO(final String uuid, final LecturePO calendarLecture, final Date lastModified) {
        this.uuid = uuid;
        lecture = calendarLecture;
        this.lastModified = lastModified;
    }

    public AppointmentPO(final String uuid, final LecturePO calendarLecture, final String name, final Date begin,
                    final Date end, final String location, final String details, final Date lastModified) {
        this.uuid = uuid;
        lecture = calendarLecture;
        this.name = name;
        this.begin = begin;
        this.end = end;
        this.location = location;
        this.details = details;
        this.lastModified = lastModified;
    }

    @Override
    public String getUuid() {
        return uuid;
    }

    public void setUuid(final String uuid) {
        this.uuid = uuid;
    }

    @Override
    @JsonIgnore
    public LecturePO getLecture() {
        return lecture;
    }

    public void setLecture(final LecturePO calendarLecture) {
        lecture = calendarLecture;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void setName(final String name) {
        this.name = name;
    }

    @Override
    public Date getBegin() {
        return begin;
    }

    @Override
    public void setBegin(final Date begin) {
        this.begin = begin;
    }

    @Override
    public Date getEnd() {
        return end;
    }

    @Override
    public void setEnd(final Date end) {
        this.end = end;
    }

    @Override
    public String getLocation() {
        return location;
    }

    @Override
    public void setLocation(final String location) {
        this.location = location;
    }

    @Override
    public String getDetails() {
        return details;
    }

    @Override
    public void setDetails(final String details) {
        this.details = details;
    }

    @Override
    public Date getLastModified() {
        return lastModified;
    }

    public void setLastModified(final Date lastModified) {
        this.lastModified = lastModified;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
        return result;
    }

    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AppointmentPO other = (AppointmentPO)obj;
        if (uuid == null) {
            if (other.uuid != null) {
                return false;
            }
        }
        else if (!uuid.equals(other.uuid)) {
            return false;
        }
        return true;
    }
}
