package de.minimum.hawapp.app.calendar.beans;

// Generated 26.04.2013 13:35:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CalendarChangemessage generated by hbm2java
 */

public class ChangeMessagePO implements ChangeMessageBO, java.io.Serializable {

    private String uuid;
    private LecturePO calendarLecture;
    private Date lastModified;
    private Date changeat;
    private String reason;
    private String what;
    private String person;

    public ChangeMessagePO() {
    }

    public ChangeMessagePO(final String uuid, final LecturePO calendarLecture, final Date lastModified) {
        this.uuid = uuid;
        this.calendarLecture = calendarLecture;
        this.lastModified = lastModified;
    }

    public ChangeMessagePO(final String uuid, final LecturePO calendarLecture, final Date lastModified,
                    final Date changeat, final String reason, final String what, final String person) {
        this.uuid = uuid;
        this.calendarLecture = calendarLecture;
        this.lastModified = lastModified;
        this.changeat = changeat;
        this.reason = reason;
        this.what = what;
        this.person = person;
    }

    @Override
    public String getUuid() {
        return uuid;
    }

    public void setUuid(final String uuid) {
        this.uuid = uuid;
    }

    @Override
    @JsonIgnore
    public LecturePO getLecture() {
        return calendarLecture;
    }

    public void setLecture(final LecturePO calendarLecture) {
        this.calendarLecture = calendarLecture;
    }

    @Override
    public Date getLastModified() {
        return lastModified;
    }

    public void setLastModified(final Date lastModified) {
        this.lastModified = lastModified;
    }

    @Override
    public Date getChangeat() {
        return changeat;
    }

    @Override
    public void setChangeat(final Date changeat) {
        this.changeat = changeat;
    }

    @Override
    public String getReason() {
        return reason;
    }

    @Override
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @Override
    public String getWhat() {
        return what;
    }

    @Override
    public void setWhat(final String what) {
        this.what = what;
    }

    @Override
    public String getPerson() {
        return person;
    }

    @Override
    public void setPerson(final String person) {
        this.person = person;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
        return result;
    }

    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ChangeMessagePO other = (ChangeMessagePO)obj;
        if (uuid == null) {
            if (other.uuid != null) {
                return false;
            }
        }
        else if (!uuid.equals(other.uuid)) {
            return false;
        }
        return true;
    }

}
