package de.minimum.hawapp.app.calendar.beans;

// Generated 26.04.2013 13:35:12 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CalendarLecture generated by hbm2java
 */

public class LecturePO implements LectureBO, java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;
    private String uuid;
    private CategoryPO category;
    private Date lastModified;
    private String name;
    private String lecturerName;
    private List<AppointmentPO> appointments = new ArrayList<AppointmentPO>(0);
    private List<ChangeMessagePO> changemessages = new ArrayList<ChangeMessagePO>(0);

    public LecturePO() {
    }

    public LecturePO(final String uuid, final CategoryPO calendarCategory, final Date lastModified) {
        this.uuid = uuid;
        category = calendarCategory;
        this.lastModified = lastModified;
    }

    public LecturePO(final String uuid, final CategoryPO calendarCategory, final Date lastModified, final String name,
                    final String lecturerName, final List<AppointmentPO> calendarAppointments,
                    final List<ChangeMessagePO> calendarChangemessages) {
        this.uuid = uuid;
        category = calendarCategory;
        this.lastModified = lastModified;
        this.name = name;
        this.lecturerName = lecturerName;
        appointments = calendarAppointments;
        changemessages = calendarChangemessages;
    }

    @Override
    public String getUuid() {
        return uuid;
    }

    public void setUuid(final String uuid) {
        this.uuid = uuid;
    }

    @Override
    @JsonIgnore
    public CategoryPO getCategory() {
        return category;
    }

    public void setCategory(final CategoryPO calendarCategory) {
        category = calendarCategory;
    }

    @Override
    public Date getLastModified() {
        return lastModified;
    }

    public void setLastModified(final Date lastModified) {
        this.lastModified = lastModified;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void setName(final String name) {
        this.name = name;
    }

    @Override
    public String getLecturerName() {
        return lecturerName;
    }

    @Override
    public void setLecturerName(final String lecturerName) {
        this.lecturerName = lecturerName;
    }

    @Override
    @JsonIgnore
    public List<AppointmentPO> getAppointments() {
        return appointments;
    }

    public void setAppointments(final List<AppointmentPO> calendarAppointments) {
        appointments = calendarAppointments;
    }

    @Override
    @JsonIgnore
    public List<ChangeMessagePO> getChangeMessages() {
        return changemessages;
    }

    public void setChangeMessages(final List<ChangeMessagePO> calendarChangemessages) {
        changemessages = calendarChangemessages;
    }

    @Override
    public String toString() {
        return name;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
        return result;
    }

    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LecturePO other = (LecturePO)obj;
        if (uuid == null) {
            if (other.uuid != null) {
                return false;
            }
        }
        else if (!uuid.equals(other.uuid)) {
            return false;
        }
        return true;
    }

}
