package de.minimum.hawapp.server.persistence.calendar;

// Generated 08.04.2013 22:52:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import de.minimum.hawapp.server.calendar.api.CategoryBO;
import de.minimum.hawapp.server.calendar.api.LectureBO;
import de.minimum.hawapp.server.calendar.api.SemesterBO;

/**
 * CategoryBO generated by hbm2java
 */
public class Category implements java.io.Serializable, CategoryBO {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
	private Semester semester;
	private String name;
	private Date lastModified;
	private Set<LectureBO> lectures = new HashSet<>(0);

	public Category() {
	}

	public Category(String uuid, Semester semester) {
		this.uuid = uuid;
		this.semester = semester;
	}

	public Category(String uuid, Semester semester, String name,
			Date lastModified, Set<LectureBO> lectures) {
		this.uuid = uuid;
		this.semester = semester;
		this.name = name;
		this.lastModified = lastModified;
		this.lectures = lectures;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public SemesterBO getSemester() {
		return this.semester;
	}

	public void setSemester(SemesterBO semester) {
		this.semester = (Semester) semester;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Set<LectureBO> getLectures() {
		return this.lectures;
	}
	@Override
	public Set<LectureBO> getLectureBOs() {
		return getLectures();
	}

	public void setLectures(Set<LectureBO> lectures) {
		this.lectures = lectures;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Category other = (Category) obj;
		if (uuid == null) {
			if (other.uuid != null)
				return false;
		} else if (!uuid.equals(other.uuid))
			return false;
		return true;
	}

	

}
