package de.minimum.hawapp.server.persistence.calendar;

// Generated 08.04.2013 22:52:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import de.minimum.hawapp.server.calendar.api.CategoryBO;
import de.minimum.hawapp.server.calendar.api.SemesterBO;

/**
 * Semester generated by hbm2java
 */

public class Semester implements java.io.Serializable, SemesterBO{


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
	private Date begin;
	private Date end;
	private Date lastModified;
	private Set<CategoryBO> categories = new HashSet<>(0);

	public Semester() {
	}

	public Semester(String uuid) {
		this.uuid = uuid;
	}

	public Semester(String uuid, Date begin, Date end, Date lastModified,
			Set<CategoryBO> categories) {
		this.uuid = uuid;
		this.begin = begin;
		this.end = end;
		this.lastModified = lastModified;
		this.categories = categories;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Set getCategories() {
		return this.categories;
	}

	@Override
	public Set<CategoryBO> getCategorieBOs() {
		
		return getCategories();
	}
	public void setCategories(Set categories) {
		this.categories = categories;
	}

	@Override
	public CategoryBO createCategory(String name) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Semester other = (Semester) obj;
		if (uuid == null) {
			if (other.uuid != null)
				return false;
		} else if (!uuid.equals(other.uuid))
			return false;
		return true;
	}

	

}
