package de.minimum.hawapp.server.persistence.calendar;

// Generated 08.04.2013 22:52:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import de.minimum.hawapp.server.calendar.api.AppointmentBO;

/**
 * Appointment generated by hbm2java
 */
public class Appointment implements java.io.Serializable, AppointmentBO{


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
	private Lecture lecture;
	private String name;
	private Date begin;
	private Date end;
	private String location;
	private String details;
	private Date lastModified;

	public Appointment() {
	}

	public Appointment(String uuid, Lecture lecture) {
		this.uuid = uuid;
		this.lecture = lecture;
	}

	public Appointment(String uuid, Lecture lecture, String name, Date begin,
			Date end, String location, String details, Date lastModified) {
		this.uuid = uuid;
		this.lecture = lecture;
		this.name = name;
		this.begin = begin;
		this.end = end;
		this.location = location;
		this.details = details;
		this.lastModified = lastModified;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public Lecture getLecture() {
		return this.lecture;
	}

	public void setLecture(Lecture lecture) {
		this.lecture = lecture;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Appointment other = (Appointment) obj;
		if (uuid == null) {
			if (other.uuid != null)
				return false;
		} else if (!uuid.equals(other.uuid))
			return false;
		return true;
	}
}
