package de.minimum.hawapp.server.persistence.calendar;

// Generated 26.04.2013 13:35:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

import de.minimum.hawapp.server.calendar.api.ChangeMessageBO;

/**
 * CalendarChangemessage generated by hbm2java
 */
@Entity
@Table(name = "calendar_changemessage", catalog = "haw_app")
public class ChangeMessagePO implements ChangeMessageBO, java.io.Serializable {


	private String uuid;
	private LecturePO calendarLecture;
	private Date lastModified;
	private Date changeat;
	private String reason;
	private String what;
	private String person;

	public ChangeMessagePO() {
	}

	public ChangeMessagePO(String uuid, LecturePO calendarLecture,
			Date lastModified) {
		this.uuid = uuid;
		this.calendarLecture = calendarLecture;
		this.lastModified = lastModified;
	}

	public ChangeMessagePO(String uuid, LecturePO calendarLecture,
			Date lastModified, Date changeat, String reason, String what,
			String person) {
		this.uuid = uuid;
		this.calendarLecture = calendarLecture;
		this.lastModified = lastModified;
		this.changeat = changeat;
		this.reason = reason;
		this.what = what;
		this.person = person;
	}

	@Id
	@Column(name = "uuid", unique = true, nullable = false)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Lecture_uuid", nullable = false)
	@JsonIgnore 
	public LecturePO getLecture() {
		return this.calendarLecture;
	}

	public void setLecture(LecturePO calendarLecture) {
		this.calendarLecture = calendarLecture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastModified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changeat", length = 19)
	public Date getChangeat() {
		return this.changeat;
	}

	public void setChangeat(Date changeat) {
		this.changeat = changeat;
	}

	@Column(name = "reason", length = 1000)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "what", length = 1000)
	public String getWhat() {
		return this.what;
	}

	public void setWhat(String what) {
		this.what = what;
	}

	@Column(name = "person")
	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChangeMessagePO other = (ChangeMessagePO) obj;
		if (uuid == null) {
			if (other.uuid != null)
				return false;
		} else if (!uuid.equals(other.uuid))
			return false;
		return true;
	}

}
