package de.minimum.hawapp.server.persistence.calendar;

// Generated 08.04.2013 22:52:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import de.minimum.hawapp.server.calendar.api.AppointmentBO;
import de.minimum.hawapp.server.calendar.api.ChangeMessageBO;
import de.minimum.hawapp.server.calendar.api.LectureBO;

/**
 * Lecture generated by hbm2java
 */
public class Lecture implements java.io.Serializable , LectureBO{

	

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String uuid;
	private Category category;
	private Date lastModified;
	private String name;
	private String lecturerName;
	private Set<AppointmentBO> appointments = new HashSet<>(0);
	private Set<ChangeMessageBO> changemessages = new HashSet<>(0);

	public Lecture() {
	}

	public Lecture(String uuid, Category category) {
		this.uuid = uuid;
		this.category = category;
	}

	public Lecture(String uuid, Category category, Date lastModified,
			String name, String lecturerName, Set<AppointmentBO> appointments,
			Set<ChangeMessageBO> changemessages) {
		this.uuid = uuid;
		this.category = category;
		this.lastModified = lastModified;
		this.name = name;
		this.lecturerName = lecturerName;
		this.appointments = appointments;
		this.changemessages = changemessages;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLecturerName() {
		return this.lecturerName;
	}

	public void setLecturerName(String lecturerName) {
		this.lecturerName = lecturerName;
	}

	public Set<AppointmentBO> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<AppointmentBO> appointments) {
		this.appointments = appointments;
	}

	public Set<ChangeMessageBO> getChangemessages() {
		return this.changemessages;
	}

	public void setChangemessages(Set<ChangeMessageBO> changemessages) {
		this.changemessages = changemessages;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uuid == null) ? 0 : uuid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lecture other = (Lecture) obj;
		if (uuid == null) {
			if (other.uuid != null)
				return false;
		} else if (!uuid.equals(other.uuid))
			return false;
		return true;
	}

	@Override
	public Set<AppointmentBO> getAppointmentBOs() {
		return ( Set<AppointmentBO>) getAppointments();
	}

	@Override
	public Set<ChangeMessageBO> getChangeMessageBOs() {
		return getChangemessages();
	}

}
